name: build docs w/ compilation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Matrix-build:
    runs-on: ubuntu-latest
    # container: node:latest 
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: checkout submodules
        run: git submodule update --init --recursive
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: false
      - name: install teqp, built from source
        run: |
          cd doc 
          conda env create
          conda activate teqpdocs || true
          cd ..
          CXX=clang++ python -m pip install .
          cd doc 
          which python
          make html
      - name: archive docs 
        run: cd doc && python -c "import shutil; shutil.make_archive('teqpdocs', 'xztar', 'build')"
      - uses: actions/upload-artifact@v3
        with:
          path: |
            ./docs/*.tar.xz
